# Generated by Django 3.2.3 on 2021-11-13 20:30

from django.db import migrations, models
import midi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MidiFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midi', models.FileField(upload_to=midi.models.user_directory_path)),
                ('midi_data', models.BinaryField(null=True)),
                ('user', models.CharField(default='', max_length=128)),
                ('source', models.CharField(default='', max_length=15)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
